export enum PreferenceGroup {
  CLASSIC_BEAUTY = "CLASSIC_BEAUTY",
  RADIANT_GLOW = "CLASSIC_BEAUTY",
  EXOTIC_VIBES = "CLASSIC_BEAUTY",
  PLAYFUL_POP = "CLASSIC_BEAUTY",
  SPORTY_FRESH = "CLASSIC_BEAUTY",
}
